import type { Metadata } from "next";
import Image from "next/image";
import SiteNav from "@/app/components/SiteNav";

export const metadata: Metadata = {
  title: "Loyalty & Retail Media Advisory — Summit Strategy Advisory",
  description:
    "Loyalty programmes and retail media for large retailers. Retained advisory against outcomes — programme design, retail media networks, AI-native retail strategy.",
  alternates: { canonical: "https://summitstrategyadvisory.com/loyalty-retail-media" },
  openGraph: {
    title: "Loyalty & Retail Media Advisory — Summit Strategy Advisory",
    description:
      "Loyalty programmes and retail media for large retailers. Retained advisory against outcomes.",
    url: "https://summitstrategyadvisory.com/loyalty-retail-media",
    images: [{ url: "/opengraph-image", width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Loyalty & Retail Media Advisory — Summit Strategy Advisory",
    description: "Loyalty programmes and retail media for large retailers. Retained advisory against outcomes.",
    images: ["/opengraph-image"],
  },
};

const BOOK_URL =
  "https://calendar.google.com/calendar/appointments/schedules/AcZssZ35rKsxptXY-OfUDUjC4G9jWqVTFtPcCPApotrNSNzoQoEvN-HAegmAab4E5jxQ7NAgSF89ollu?gv=true";

const pageSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  name: "Loyalty & Retail Media Advisory",
  dateModified: "2026-04-29",
  provider: {
    "@type": "Organization",
    name: "Summit Strategy Advisory",
    url: "https://summitstrategyadvisory.com",
  },
  description:
    "Retained advisory for loyalty programmes and retail media networks at large retailers. Programme design, AI quick wins, and net-new revenue capability build.",
  areaServed: ["Canada", "United States"],
  serviceType: "Management Consulting",
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is a retail media network?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "A retail media network is an advertising platform operated by a retailer that allows suppliers and brands to purchase advertising placements using the retailer's first-party customer data. Examples include Amazon Advertising, Walmart Connect, and Kroger Precision Marketing. Retail media is one of the fastest-growing advertising channels globally, projected to reach $128B by 2026 (eMarketer).",
      },
    },
    {
      "@type": "Question",
      name: "How do you measure loyalty programme ROI?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Loyalty ROI is measured by isolating incremental spend — the revenue generated by members above the baseline they would have spent without the programme. Summit's Loyalty Economics Diagnostic methodology identifies this attributable revenue, which is typically undercounted by 20–40% in traditional analyses. Loyalty programme members spend 12–18% more than non-members on average (Bond Loyalty Report).",
      },
    },
    {
      "@type": "Question",
      name: "How long does a loyalty programme review take?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Summit's Programme Review & Roadmap engagement typically runs 4–6 weeks and delivers a complete diagnostic of programme effectiveness, revenue lift and advertising opportunity sizing, and a prioritised capability roadmap. Most clients start to see quick-win opportunities within the first two weeks.",
      },
    },
    {
      "@type": "Question",
      name: "What is the difference between loyalty and retail media?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Loyalty programmes reward customers for repeat purchases and generate first-party behavioural data. Retail media monetises that data by selling advertising placements to suppliers and brands. The two are complementary — a richer loyalty programme creates more valuable audience segments for a retail media network. Retailers with mature loyalty programmes typically generate 40–60% higher retail media CPMs than those without.",
      },
    },
    {
      "@type": "Question",
      name: "How does Summit's retained advisory model work?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Summit works on a monthly retainer against a defined set of objectives. Engagements are scoped to a clear outcome — a programme review, a network launch, an AI capability build — rather than open-ended hours. Most engagements run 4–12 weeks. Clients retain Summit for as long as the work requires, then exit cleanly.",
      },
    },
  ],
};

const focusAreas = [
  { tag: "Review & Recommendation", title: "Audit. Diagnose. Recommend.", body: "We assess your loyalty program, retail media capability, or technology stack — finding the gaps, quantifying the opportunity, and delivering a clear set of prioritised recommendations. Not a report that sits on a shelf. A blueprint you can act on." },
  { tag: "Supercharge with AI", title: "AI That Earns Its Keep.", body: "We identify the AI quick wins that lift team and programme performance today, and help you blueprint the bigger bets — personalisation engines, predictive analytics, supplier optimisation — that drive compounding growth over time." },
  { tag: "New Revenue Builds", title: "Build New Revenue Streams.", body: "We design and build net-new revenue capabilities alongside your team — supplier loyalty programmes, retail media networks, marketplace models, and subscription plays. We don't just advise on these. We've built them." },
];

const caseStudies = [
  {
    client: "Global Grocery Retailer",
    region: "North America",
    tag: "Loyalty",
    challenge: "Loyalty program generating high engagement but low incremental sales. Leadership questioned the ROI of the entire program.",
    outcome: "Loyalty Economics Diagnostic revealed $40M+ in attributable incremental revenue previously uncounted. Program retained and scaled.",
    metrics: ["$40M+ incremental revenue identified", "Program strategy overhauled", "Board-level ROI case built"],
  },
  {
    client: "Specialty Retailer",
    region: "North America",
    tag: "Retail Media",
    challenge: "Supplier relationships strong but no formalised media network. Revenue from suppliers was ad hoc and underpriced.",
    outcome: "Supplier-Funded Media Venture engagement surfaced $8M in near-term revenue opportunity and a clear network launch roadmap.",
    metrics: ["$8M revenue opportunity mapped", "12 priority supplier partnerships identified", "Network launched within 6 months"],
  },
];

const faqs = faqSchema.mainEntity;

export default function LoyaltyRetailMediaPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <SiteNav />
      <div className="page">
        <div className="inner">
          <div className="inner-hero">
            <div className="inner-eyebrow">For Retailers</div>
            <h1 className="inner-title">Loyalty & Retail Media</h1>
            <p className="inner-lead">
              Loyalty programs and retail media for large retailers. We&apos;ve surfaced $40M in
              uncounted loyalty revenue and built retail media networks that generate real supplier
              income. Now we build them with you.
            </p>
            <p style={{ fontFamily: "var(--font-dm-sans), sans-serif", fontSize: 13, color: "rgba(255,255,255,0.45)", marginTop: 16 }}>
              Last reviewed: April 2026 · By{" "}
              <a href="/" style={{ color: "rgba(255,255,255,0.55)", textDecoration: "underline" }}>
                Anthony Stevenson
              </a>
              , Founder, Summit Strategy Advisory
            </p>
          </div>

          <div className="inner-body">
            <h2 className="section-label">Our Focus</h2>
            <p className="section-intro">
              Three areas where we go deep. Every engagement maps to one of these — often more than one.
            </p>
            <div className="focus-grid">
              {focusAreas.map((f) => (
                <div className="focus-card" key={f.title}>
                  <span className="resource-tag" style={{ marginBottom: 14, display: "inline-block" }}>{f.tag}</span>
                  <div className="focus-title">{f.title}</div>
                  <p className="focus-body">{f.body}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="equity-band">
            <div className="inner-body" style={{ paddingTop: 0, paddingBottom: 0 }}>
              <h2 className="section-label" style={{ color: "var(--sage)" }}>The Market Opportunity</h2>
              <p style={{ fontFamily: "var(--font-barlow-condensed), sans-serif", fontSize: "clamp(26px, 4vw, 40px)", fontWeight: 800, color: "#fff", lineHeight: 1.15, maxWidth: 640, marginBottom: 24 }}>
                Retail media is the fastest-growing ad channel in the world.
              </p>
              <p style={{ color: "rgba(255,255,255,0.6)", fontSize: 16, lineHeight: 1.7, maxWidth: 620, marginBottom: 12 }}>
                Global retail media ad spend is projected to reach $128B by 2026, growing at 21% annually
                (eMarketer, 2024). Yet most retailers outside the top 10 have not yet built a formalised
                media network — leaving significant supplier revenue on the table.
              </p>
              <p style={{ color: "rgba(255,255,255,0.6)", fontSize: 16, lineHeight: 1.7, maxWidth: 620, marginBottom: 40 }}>
                Loyalty programme members spend 12–18% more than non-members on average (Bond Loyalty
                Report). The programmes that capture that incremental lift are those with clear mechanics,
                strong data infrastructure, and a measurement model that counts it correctly.
              </p>
              <div className="equity-cards">
                <div className="equity-card"><div className="equity-card-num">$128B</div><div className="equity-card-label">Global retail media by 2026</div></div>
                <div className="equity-card"><div className="equity-card-num">21%</div><div className="equity-card-label">Annual retail media growth</div></div>
                <div className="equity-card"><div className="equity-card-num">12–18%</div><div className="equity-card-label">Loyalty member spend uplift</div></div>
              </div>
            </div>
          </div>

          <div className="inner-body">
            <h2 className="section-label">Case Studies</h2>
            <p className="section-intro">
              A sample of what we&apos;ve delivered. Details anonymised at client request.
            </p>
            <div className="retail-cases">
              {caseStudies.map((c) => (
                <div className="retail-case" key={c.client}>
                  <div className="retail-case-header">
                    <div>
                      <div className="retail-case-client">{c.client}</div>
                      <div className="retail-case-region">{c.region}</div>
                    </div>
                    <span className="resource-tag">{c.tag}</span>
                  </div>
                  <div className="retail-case-body">
                    <div className="retail-case-col">
                      <div className="retail-case-col-label">The Challenge</div>
                      <p className="retail-case-text">{c.challenge}</p>
                    </div>
                    <div className="retail-case-col">
                      <div className="retail-case-col-label">The Outcome</div>
                      <p className="retail-case-text">{c.outcome}</p>
                    </div>
                  </div>
                  <div className="case-outcomes" style={{ marginTop: 20 }}>
                    {c.metrics.map((m) => (
                      <div className="case-outcome" key={m}>{m}</div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <p style={{ fontFamily: "var(--font-dm-sans), sans-serif", fontSize: 14, color: "var(--ghost)", marginTop: 24, lineHeight: 1.7 }}>
              Use Summit&apos;s free{" "}
              <a href="/tools/positioning" style={{ color: "var(--teal)", fontWeight: 600 }}>Positioning Statement Grader</a>{" "}
              to sharpen how you communicate your loyalty or retail media capability to internal stakeholders.
            </p>
          </div>

          {/* FAQ section */}
          <div className="inner-body">
            <h2 className="section-label">Frequently Asked Questions</h2>
            <div className="features">
              {faqs.map((faq) => (
                <div className="feature" key={faq.name}>
                  <div className="feature-title">{faq.name}</div>
                  <p className="feature-body">{faq.acceptedAnswer.text}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="calendly-band">
            <div className="inner-body" style={{ paddingTop: 0, paddingBottom: 0 }}>
              <div className="calendly-content">
                <div>
                  <h2 className="section-label" style={{ color: "var(--sage)" }}>Book a Meeting</h2>
                  <p className="calendly-title" style={{ fontFamily: "var(--font-barlow-condensed), sans-serif", fontSize: "clamp(26px, 4vw, 40px)", fontWeight: 800, color: "#fff", lineHeight: 1.15, marginBottom: 16 }}>
                    Let&apos;s talk about your retail challenge.
                  </p>
                  <p className="calendly-body">
                    A 30-minute call is enough to know if there&apos;s a fit. No deck, no pitch —
                    just a direct conversation about what you&apos;re trying to solve.
                  </p>
                </div>
                <a href={BOOK_URL} target="_blank" rel="noopener noreferrer" className="calendly-btn">
                  Book a 30-Minute Call →
                </a>
              </div>
            </div>
          </div>
        </div>

        <footer className="footer">
          <Image src="/brand-icons/Combination Mark_White.png" alt="Summit Strategy Advisory" width={140} height={22} className="footer-logo" />
          <ul className="footer-links">
            <li><a href="/ai-studio">AI Studio</a></li>
            <li><a href="/loyalty-retail-media">Loyalty & Retail Media</a></li>
            <li><a href="/scale-up-advisory">Scale-Up Advisory</a></li>
            <li><a href="/tools">GTM Tools</a></li>
            <li><a href="/newsletter">Newsletter</a></li>
          </ul>
          <span className="footer-copy">© 2026 Summit Strategy Advisory</span>
        </footer>
      </div>
    </>
  );
}
